name: Cloudflare Gateway Adblock Updater

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          repository: 'SeriousHoax/Cloudflare-Gateway-Adblock-Updater'
          ref: 'main'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Tools
        run: pip install requests aiohttp

      - name: Create Config and Run
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          cat << 'EOF' > config.json
          {
            "blocklists": [
              {
                "name": "Hagezi Pro++",
                "url": "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/pro.plus-onlydomains.txt"
              }
            ],
            "rule_name": "Hagezi Pro++ Adblock",
            "rule_precedence": 10000,
            "fresh_start": false,
            "check_versions": true
          }
          EOF
          python update_gateway.py
